from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addEditCoffee(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.statusEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.statusEdit.setReadOnly(True)
        self.statusEdit.setObjectName("statusEdit")
        self.horizontalLayout_3.addWidget(self.statusEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sortEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sortEdit.setObjectName("sortEdit")
        self.verticalLayout.addWidget(self.sortEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.degreeBox = QtWidgets.QComboBox(self.centralwidget)
        self.degreeBox.setObjectName("degreeBox")
        self.degreeBox.addItem("")
        self.degreeBox.addItem("")
        self.degreeBox.addItem("")
        self.verticalLayout.addWidget(self.degreeBox)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.conBox = QtWidgets.QComboBox(self.centralwidget)
        self.conBox.setObjectName("conBox")
        self.conBox.addItem("")
        self.conBox.addItem("")
        self.verticalLayout.addWidget(self.conBox)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.descPlainEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.descPlainEdit.setObjectName("descPlainEdit")
        self.verticalLayout.addWidget(self.descPlainEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.priceBox = QtWidgets.QSpinBox(self.centralwidget)
        self.priceBox.setMaximum(10000)
        self.priceBox.setObjectName("priceBox")
        self.horizontalLayout.addWidget(self.priceBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.volBox = QtWidgets.QSpinBox(self.centralwidget)
        self.volBox.setMaximum(500)
        self.volBox.setObjectName("volBox")
        self.horizontalLayout_2.addWidget(self.volBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setObjectName("saveBtn")
        self.verticalLayout.addWidget(self.saveBtn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Текущее состояние: "))
        self.label.setText(_translate("MainWindow", "Название сорта:"))
        self.label_2.setText(_translate("MainWindow", "Степень обжарки:"))
        self.degreeBox.setItemText(0, _translate("MainWindow", "Светлая"))
        self.degreeBox.setItemText(1, _translate("MainWindow", "Средняя"))
        self.degreeBox.setItemText(2, _translate("MainWindow", "Темная"))
        self.label_3.setText(_translate("MainWindow", "Вид:"))
        self.conBox.setItemText(0, _translate("MainWindow", "В зернах"))
        self.conBox.setItemText(1, _translate("MainWindow", "Молотый"))
        self.label_4.setText(_translate("MainWindow", "Описание вкуса:"))
        self.label_5.setText(_translate("MainWindow", "Цена:"))
        self.label_6.setText(_translate("MainWindow", "Объем упаковки:"))
        self.saveBtn.setText(_translate("MainWindow", "Сохранить"))
